env_template

@trivial Fixing the env template

---

src/components/container/_container.scss

CQ-4351689 Enable responsiveness for forms guide container component.

---

.parcelrc

[CQ-4351792] fix build structure

---

src/components/wizard/_wizard.scss
src/site/_variables.scss

fix color issue

---

src/components/accordion/_accordion.scss
src/components/checkboxgroup/_checkboxgroup.scss
src/components/footer/_footer.scss
src/components/tabsontop/_tabsontop.scss
src/components/verticaltabs/_verticaltabs.scss
src/components/wizard/_wizard.scss

[FORM-9062] fix accessibility issue

---

src/components/checkbox/_checkbox.scss
src/theme.scss

FORMS-9688 canvas theme for checkbox

---

src/components/panelcontainer/_panelcontainer.scss
src/site/_variables.scss

FORMS-9473: updated margin for panel container

---

src/components/accordion/_accordion.scss
src/components/checkboxgroup/_checkboxgroup.scss
src/components/radiobutton/_radiobutton.scss
src/components/tabsontop/_tabsontop.scss

CHANGE IN WIDTH FOR RESPONSIVE DESIGN

---

src/components/accordion/_accordion.scss
src/components/button/_button.scss
src/components/checkbox/_checkbox.scss
src/components/checkboxgroup/_checkboxgroup.scss
src/components/container/_container.scss
src/components/datepicker/_datepicker.scss
src/components/dropdown/_dropdown.scss
src/components/emailinput/_emailinput.scss
src/components/fileinput/_fileinput.scss
src/components/numberinput/_numberinput.scss
src/components/pageheader/_pageheader.scss
src/components/panelcontainer/_panelcontainer.scss
src/components/radiobutton/_radiobutton.scss
src/components/recaptcha/_recaptcha.scss
src/components/tabsontop/_tabsontop.scss
src/components/telephoneinput/_telephoneinput.scss
src/components/textinput/_textinput.scss
src/components/verticaltabs/_verticaltabs.scss
src/components/wizard/_wizard.scss

[FORMS-10587] update css for RTL

---

src/components/accordion/_accordion.scss
src/components/button/_button.scss
src/components/checkbox/_checkbox.scss
src/components/checkboxgroup/_checkboxgroup.scss
src/components/datepicker/_datepicker.scss
src/components/dropdown/_dropdown.scss
src/components/emailinput/_emailinput.scss
src/components/fileinput/_fileinput.scss
src/components/numberinput/_numberinput.scss
src/components/panelcontainer/_panelcontainer.scss
src/components/radiobutton/_radiobutton.scss
src/components/recaptcha/_recaptcha.scss
src/components/tabsontop/_tabsontop.scss
src/components/telephoneinput/_telephoneinput.scss
src/components/textinput/_textinput.scss
src/components/verticaltabs/_verticaltabs.scss
src/components/wizard/_wizard.scss

[FORMS-10833] update theme for backward compatibility

---

src/components/accordion/_accordion.scss
src/components/wizard/_wizard.scss

fix hidden accordion issue for headless

---

.github/workflows/rtl-compatibility.yml
.stylelintrc.json
package-lock.json
package.json
src/site/_base.scss
src/site/_fonts.scss
src/site/_grid.scss
src/site/_variables.scss

- check https://github.com/stylelint/stylelint-config-standard/issues/214 @review @vdua
DOD(Yes)

Added support for stylelint to use logical specification

---

src/site/_base.scss
src/site/_grid.scss

add rtl in grid

---

src/components/checkbox/_checkbox.scss
src/components/checkboxgroup/_checkboxgroup.scss
src/components/datepicker/_datepicker.scss
src/components/dropdown/_dropdown.scss
src/components/emailinput/_emailinput.scss
src/components/fileinput/_fileinput.scss
src/components/numberinput/_numberinput.scss
src/components/radiobutton/_radiobutton.scss
src/components/recaptcha/_recaptcha.scss
src/components/telephoneinput/_telephoneinput.scss
src/components/textinput/_textinput.scss

fix RTL border issue

---

src/components/termsandconditions/_termsandconditions.scss
src/site/_variables.scss
src/theme.scss

Terms and Conditions Canvas Theme Support

---

.github/workflows/publish.yml

workflow for publish theme

---

src/components/container/_container.scss

publish theme

---

src/components/switch/_switch.scss
src/site/_variables.scss
src/theme.scss

added css for switch component

---

src/theme.ts

New line added

---

src/theme.scss

check publish workflow

---

src/components/fileinput/_fileinput.scss

fix rtl issues

---

package.json

Fixed using browserlist config as suggested by https://github.com/parcel-bundler/parcel/issues/9157

FORMS-13587 - Device Emulator not working for Core components based Forms

---

src/components/datepicker/_datepicker.scss

FORMS-13763 - UI Misalignment of Date Picker Field in AEM Forms

---

src/components/hcaptcha/_hcaptcha.scss
src/theme.scss

Add scss for hCaptcha core component

---

src/components/textinput/_textinput.scss

Multiline Textbox Can Be Stretched Beyond Containing Panel

---

src/theme.scss

release theme

---

src/components/tabsontop/_tabsontop.scss
src/components/verticaltabs/_verticaltabs.scss
src/components/wizard/_wizard.scss
src/site/_mixin.scss
src/theme.scss

Stepped support in tabs/wizard

---

src/components/container/_container.scss

fix: hamburger menu hide tabs in mobile view

---

src/components/switch/_switch.scss
src/site/_variables.scss

FORMS-18703: State of active component lacks 3 to 1 contrast ratio @sunnym @vavarshn

---

src/components/scribble/_scribble.scss

Scribble CSS

---

src/components/accordion/_accordion.scss

https://jira.corp.adobe.com/browse/FORMS-18693

FORMS-18693: Desktop, RWD Tablet, RWD Mobile - An icon lacks 3 to 1 contrast ratio @sunnym @vavarshn

---

src/site/_variables.scss

https://jira.corp.adobe.com/browse/FORMS-18674

FORMS-18674: Focus indicator lacks 3 to 1 contrast ratio @sunnym @vavarshn

---

src/components/fileinput/_fileinput.scss

https://jira.corp.adobe.com/browse/FORMS-18709

FORMS-18709: Large text content lacks 3:1 contrast ratio @sunnym @vavarshn

---

src/components/accordion/_accordion.scss
src/components/button/_button.scss
src/components/checkbox/_checkbox.scss
src/components/checkboxgroup/_checkboxgroup.scss
src/components/datepicker/_datepicker.scss
src/components/dropdown/_dropdown.scss
src/components/emailinput/_emailinput.scss
src/components/fileinput/_fileinput.scss
src/components/hcaptcha/_hcaptcha.scss
src/components/numberinput/_numberinput.scss
src/components/panelcontainer/_panelcontainer.scss
src/components/radiobutton/_radiobutton.scss
src/components/recaptcha/_recaptcha.scss
src/components/switch/_switch.scss
src/components/tabsontop/_tabsontop.scss
src/components/telephoneinput/_telephoneinput.scss
src/components/termsandconditions/_termsandconditions.scss
src/components/textinput/_textinput.scss
src/components/turnstile/_turnstile.scss
src/components/verticaltabs/_verticaltabs.scss
src/components/wizard/_wizard.scss

https://jira.corp.adobe.com/browse/FORMS-18648

FORMS-18648: Desktop, RWD Tablet, RWD Mobile - Text content lacks 4.5:1 contrast ratio @sunnym @vavarshn

---

src/components/switch/_switch.scss
src/site/_variables.scss

https://jira.corp.adobe.com/browse/FORMS-18707

FORMS-18707: State of active component lacks 3 to 1 contrast ratio @sunnym @vavarshn

---

src/site/_variables.scss

https://jira.corp.adobe.com/browse/FORMS-18637

FORMS-18637: Desktop, RWD Tablet, RWD Mobile - Text content lacks 4.5:1 contrast ratio @sunnym @vavarshn

---

src/components/wizard/_wizard.scss
src/resources/images/Chevron-Left.svg
src/resources/images/Chevron-Right.svg

https://jira.corp.adobe.com/browse/FORMS-18818

FORMS-18818: An icon lacks 3 to 1 contrast ratio @sunnym @vavarshn

---

src/components/wizard/_wizard.scss
src/resources/images/Chevron-Left-White.svg

https://jira.corp.adobe.com/browse/FORMS-18816

FORMS-18816: State of active component lacks 3 to 1 contrast ratio @sunnym @vavarshn

---

src/components/scribble/_scribble.scss

Removed comment.
